version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: lmsuser
      POSTGRES_PASSWORD: lmspassword
      POSTGRES_DB: lmsdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - lms-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
      - DATABASE_URL=postgresql://lmsuser:lmspassword@db:5432/lmsdb
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    networks:
      - lms-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:5000
      - NODE_ENV=development
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge

volumes:
  db_data:
