version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: lmsuser
      POSTGRES_PASSWORD: lmspassword
      POSTGRES_DB: lmsdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: lmsuser
      DB_PASSWORD: lmspassword
      DB_NAME: lmsdb
      FLASK_ENV: development
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: flask run --host=0.0.0.0 --port=5000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://backend:5000
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm run dev -- --host --port 3000
volumes:
  db_data:
